CELERY_APP="scrapper"
CELERY_BIN="/home/rozen/Python/Architecture/Multi-Worker-Thread/.venv/bin/celery"

# define 2 worker
CELERYD_NODES="worker1"

# setting for log and PID
CELERYD_PID_FILE="/home/rozen/Python/Architecture/Multi-Worker-Thread/logs/worker/run/%n.pid"
CELERYD_LOG_FILE="/home/rozen/Python/Architecture/Multi-Worker-Thread/logs/worker/log/%n%I.log"
CELERYD_LOG_LEVEL="INFO"

# option for both worker
# -c = concurrency, -P = pool, -Q = queue
# CELERYD_OPTS="-c:worker1 10 -P:worker1 threads -Q:worker1 dowload-upload \
#               -c:worker2 20 -P:worker2 threads"

CELERYD_OPTS="-c:worker1 10 -P:worker1 threads"
